name = "whosentmeadollar"
main = "worker.js"
compatibility_date = "2026-09-18"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "JOINS"
id = "ec7d9c931db249cab5212a5655679a4e"
